### ISSUE TITLE
Existing Sa11y project

### ISSUE THREAD

**Issue by jasonschroeder-sfdc** [ryersondmp/sa11y#39] opened 2022-10-05 21:00 UTC
Hi, there is another project with the same goals at https://github.com/salesforce/sa11y which predates this package. Can we work together, or would you consider renaming your project?

**Comment by adamchaboryk** [comment] 2022-10-07 14:47
Hey @jasonschroeder-sfdc, 

If we are checking the commit history, it appears my project predates yours by a few days. My repository was created on March 9, 2020. Salesforce created its repository on March 12, 2020. My project was also first publicly advertised on Global Accessibility Awareness Day on May 21st in 2020.  

For your convenience, here are links to the very first commits of both repositories: 
- Sa11y by TMU (formerly Ryerson University): https://github.com/ryersondmp/sa11y/commit/1395a6290224d10664befc5de283bfa232caae30 (Verified by GitHub on March 9)
- Sa11y by Salesforce: https://github.com/salesforce/sa11y/commit/099a6dafe6f206a8f34d649327f5893001b78c77 (Committed on March 12)

You can also use the following tool to confirm the creation dates of both of our repositories: https://www.syncwithtech.org/github-repos-size-creation-date/#bookmarklet

Our projects indeed share a common goal of making the web more accessible, but in my opinion, our projects are vastly different in my ways. Sa11y by Salesforce is a comprehensive testing library for developers (with output in terminal), whereas my project strictly checks for content accessibility issues and is geared towards content editors (GUI based). Feel free to learn more about Sa11y by visiting our project webpage: https://sa11y.netlify.app/  

I know Salesforce is also a big supporter of academic institutions like TMU where our Sa11y was started. So I am happy to explore how we can collaborate and help advance the cause of digital accessibility.

I also understand the technical challenges of renaming a repository, and it would be a big ask. Therefore, I am OK with Salesforce using Sa11y. Although to prevent confusion, I would suggest using your long name or a variation of it when advertising, for example: Sa11y Automated Accessibility Testing, SalesForce Sa11y, Salesforce A11y, etc. 

Happy Friday!

**Closed** 2022-12-08 16:18 UTC
