### ISSUE TITLE
Not working when JS changes the DOM

### ISSUE THREAD

**Issue by markconroy** [ryersondmp/sa11y#40] opened 2022-10-19 10:51 UTC
Hi,

Thanks for this library, it's great. 

One issue we have found is that if our JS changes the DOM sa11y doesn't breaks it. Here's my example:

I have an accordion, which uses `h3` for the accordion title and leave the accordion body visible. Then, if JS is available, we use progressive enhancement to grab this `h3`, create a `button` element, and wrap the `h3` with the button element, and hide the accordion body. This button is then used to as the trigger to show/hide the accordion body.

However, sa11y is doing 2 things (I think):
1. It reads the rendered HTML that the server sends, so is reading the `h3` and not the updated element which now has a button, and
2. It stops the event listener on the button from working. `button.addEventListener('click', ...)` doesn't do anything any more.

We can fix it by:
1. Creating the button within the HTML (but we'd prefer not to do that for progressive enhancement reasons), or
2. Adding `.accordion` to the `containerIgnore` array (this is what we've currently done while figuring out a better fix (hence this issue!)

Have you any thoughts on this, or how we might get sa11y to work with the updated DOM?

**Comment by adamchaboryk** [comment] 2022-10-19 16:01
Hey @markconroy,

Thanks for the feedback and reporting the bug! 

It's a strange bug, but I managed to replicate the issue and determined that my ruleset that flags excessive all caps text is the cause. 

In the meantime, if you set `allCapsQA: false' that should fix it. Although I'll have a proper fix for this next release. I'll keep you posted.

Cheers!

**Comment by markconroy** [comment] 2022-10-19 18:01
You're a star. Thanks so much for the quick response.

**Comment by adamchaboryk** [comment] 2022-10-19 22:07
It should be fixed now! 🙂

Please let me know if you come across any other issues (or have any other feedback)!

**Closed by adamchaboryk** 2022-10-19 22:07 UTC

**Comment by markconroy** [comment] 2022-10-20 10:27
Works a treat. Thanks.
